/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 48381db6087a66a6fd04020368fcf3be)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "ReviewOrchestrator" | "SecurityAgent" | "LogicAgent" | "PerformanceAgent" | "PatternAgent";
	}
	interface Env {
		AI: Ai;
		ReviewOrchestrator: DurableObjectNamespace<import("./src/server/index").ReviewOrchestrator>;
		SecurityAgent: DurableObjectNamespace<import("./src/server/index").SecurityAgent>;
		LogicAgent: DurableObjectNamespace<import("./src/server/index").LogicAgent>;
		PerformanceAgent: DurableObjectNamespace<import("./src/server/index").PerformanceAgent>;
		PatternAgent: DurableObjectNamespace<import("./src/server/index").PatternAgent>;
		REVIEW_WORKFLOW: Workflow<Parameters<import("./src/server/index").ReviewWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
