/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 56b44de2bf5317aa8fed05cd9c842fac)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "ReviewOrchestrator" | "SecurityAgent" | "LogicAgent" | "PerformanceAgent" | "PatternAgent" | "SummaryAgent";
	}
	interface Env {
		AI: Ai;
		DEEPSEEK_API_KEY: string;
		ReviewOrchestrator: DurableObjectNamespace<import("./src/server/index").ReviewOrchestrator>;
		SecurityAgent: DurableObjectNamespace<import("./src/server/index").SecurityAgent>;
		LogicAgent: DurableObjectNamespace<import("./src/server/index").LogicAgent>;
		PerformanceAgent: DurableObjectNamespace<import("./src/server/index").PerformanceAgent>;
		PatternAgent: DurableObjectNamespace<import("./src/server/index").PatternAgent>;
		SummaryAgent: DurableObjectNamespace<import("./src/server/index").SummaryAgent>;
		REVIEW_WORKFLOW: Workflow<Parameters<import("./src/server/index").ReviewWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_API_KEY">> {}
}
